name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: unbuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "Done - bye"
